# 自定义配置
application.api.secret: =================+++++++++---->>>>chenzz@cnsibo.com<<<<<---+++++++++++================

# ==============================================================================
# 项目相关配置
cnsibo:
    # 名称
    name: sibo-admin
    # 版本
    version: 1.0.0
    # 版权年份
    copyrightYear: 2018
    # 头像上传路径
    profile: D:/profile/
    # 获取ip地址开关
    addressEnabled: true

# ==============================================================================
# 数据源配置
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        druid:
            # 主库数据源
            master:
                #url: jdbc:mysql://localhost:3306/sibo-gxy-2?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                #url: jdbc:mysql://39.104.163.194:3306/sibo-gxy?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                #username: sibo-gxy
                #password: sibo-gxy
                url: jdbc:mysql://192.168.3.200:3306/sibo-test-xx?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
                username: root
                password: root
            # 从库数据源
            slave:
                # 从数据源开关/默认关闭
                enabled: false
                url: 
                username: 
                password: 
            # 初始连接数
            initial-size: 10
            # 最大连接池数量
            max-active: 100
            # 最小连接池数量
            min-idle: 10
            # 配置获取连接等待超时的时间
            max-wait: 60000
            # 打开PSCache，并且指定每个连接上PSCache的大小
            pool-prepared-statements: true
            max-pool-prepared-statement-per-connection-size: 20
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            timeBetweenEvictionRunsMillis: 60000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            min-evictable-idle-time-millis: 300000
            validation-query: SELECT 1 FROM DUAL
            test-while-idle: true
            test-on-borrow: false
            test-on-return: false
            stat-view-servlet:
                enabled: true
                url-pattern: /monitor/druid/*
            filter:
                stat:
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: false
                wall:
                    config:
                        multi-statement-allow: true

#aliyun
aliyun.accessKey.id: LTAIFYqytsUOAI8T
aliyun.accessKey.secret: L4d41D9u9zswDBhn23Od0lcWFFgq7H
aliyun.sms.template.code: SMS_149375256
aliyun.sms.template.login: SMS_149375256
aliyun.sms.template.sos: SMS_152281154
aliyun.sms.template.sos.xueya: SMS_153995473
aliyun.sms.template.sos.time: SMS_153331950
aliyun.sms.sign.name.code: 思博智创

netty:
    port: 8001
    host: 127.0.0.1